Repository scverse/pertpy, pull requests merged in 2023-11, with the labels that each got.

#419 Add cinemaot nb
  docs/_static/tutorials/cinemaot.png
  docs/conf.py
  docs/tutorials/index.md
Labels: enhancement, chore

#422 scope imports of ete3 in tasccoda
  pertpy/plot/__init__.py
  pertpy/plot/_coda.py
  pertpy/tools/__init__.py
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_tasccoda.py
Labels: enhancement

#423 Added example for pt.pl.milo.nhood_graph
  pertpy/plot/_milopy.py
  pertpy/tools/_distances/_distances.py
Labels: enhancement

#432 Fix code coverage
  .github/workflows/test.yml
  codecov.yml
  pyproject.toml
  tests/__init__.py
Labels: bug

#433 Docs examples for CINEMA-OT
  pertpy/plot/_cinemaot.py
  pertpy/tools/_cinemaot.py
  pertpy/tools/_dialogue.py
Labels: enhancement

#443 Removed scGen batch removal tutorial from gallery
  docs/_static/tutorials/scgen_batch_removal.png
  docs/conf.py
  docs/tutorials/index.md
Labels: chore

#450 Added smillie_2019 dataloader and renamed smillie dataset to tasccoda_example
  pertpy/data/__init__.py
  pertpy/data/_datasets.py
  pertpy/plot/_coda.py
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_tasccoda.py
  tests/tools/_coda/test_tasccoda.py
Labels: enhancement
