Repository scverse/pertpy, pull requests merged in 2023-09, with the labels that each got.

#362 Remove statsannotations
  pertpy/plot/_coda.py
  pyproject.toml
Labels: enhancement

#366 scCODA: add low/high acceptance probability warnings
  pertpy/tools/_coda/_base_coda.py
Labels: bug

#368 DIALOGUE extensions and plots
  docs/usage/usage.md
  pertpy/plot/__init__.py
  pertpy/plot/_dialogue.py
  pertpy/plot/_mixscape.py
  pertpy/tools/_dialogue.py
Labels: enhancement, chore

#374 Fix stephenson 2021 and refactor
  pertpy/data/_datasets.py
Labels: bug, enhancement
