Repository scverse/pertpy, pull requests merged in 2023-12, with the labels that each got.

#453 DiscriminatorClassifier compatibility with sparse matrices
  pertpy/tools/_perturbation_space/_discriminator_classifier.py
Labels: bug

#455 CentroidSpace AnnData Annotations
  pertpy/tools/_perturbation_space/_simple.py
Labels: bug

#456 New plotting API
  .pre-commit-config.yaml
  pertpy/__init__.py
  pertpy/plot/__init__.py
  pertpy/plot/_augur.py
  pertpy/plot/_coda.py
  pertpy/plot/_dialogue.py
  pertpy/plot/_guide_rna.py
  pertpy/plot/_milopy.py
  pertpy/plot/_mixscape.py
  pertpy/preprocessing/_guide_rna.py
  pertpy/tools/_augur.py
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_dialogue.py
  pertpy/tools/_milo.py
  pertpy/tools/_mixscape.py
Labels: enhancement

#464 Make dialogue's load protected
  pertpy/tools/_dialogue.py
Labels: enhancement

#465 Docs improvements for perturbation space
  pertpy/tools/_perturbation_space/_discriminator_classifier.py
  pertpy/tools/_perturbation_space/_perturbation_space.py
  pertpy/tools/_perturbation_space/_simple.py
Labels: enhancement

#472 Fix subsetting of milo.plot_da_beeswarm
  pertpy/tools/_milo.py
Labels: bug

#471 PertSpace docs improvements
  pertpy/tools/_perturbation_space/_clustering.py
  pertpy/tools/_perturbation_space/_discriminator_classifier.py
  pertpy/tools/_perturbation_space/_perturbation_space.py
  pertpy/tools/_perturbation_space/_simple.py
Labels: enhancement

#397 bug fixes, implementation tweaks, and additional distances
  pertpy/tools/_distances/_distances.py
  tests/tools/_distances/test_distance_tests.py
  tests/tools/_distances/test_distances.py
  tests/tools/test_milo.py
Labels: bug, chore

#477 Add DE filtering
  pertpy/tools/_differential_gene_expression.py
  pertpy/tools/decoupler_LICENSE
Labels: enhancement

#475 Fix/discriminator classifier nn dimensions
  pertpy/tools/_perturbation_space/_discriminator_classifier.py
  tests/tools/_perturbation_space/test_discriminator_classifier.py
Labels: bug
