Repository scverse/pertpy, pull requests merged in 2023-10, with the labels that each got.

#387 fix naming of example data in doc examples
  pertpy/tools/_distances/_distances.py
Labels: bug

#393 Installation Apple Silicon
  docs/contributing.md
  docs/installation.md
Labels: chore

#398 Speed up tests by subsampling
  docs/installation.md
  tests/tools/_coda/test_sccoda.py
  tests/tools/_coda/test_tasccoda.py
  tests/tools/test_cinemaot.py
Labels: enhancement, chore

#391 Documentation examples
  pertpy/plot/_augur.py
  pertpy/plot/_coda.py
  pertpy/plot/_dialogue.py
  pertpy/plot/_guide_rna.py
  pertpy/plot/_milopy.py
  pertpy/plot/_mixscape.py
  pertpy/plot/_scgen.py
  pertpy/preprocessing/_guide_rna.py
  pertpy/tools/_augur.py
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_sccoda.py
  pertpy/tools/_coda/_tasccoda.py
  pertpy/tools/_dialogue.py
  pertpy/tools/_distances/_distance_tests.py
  pertpy/tools/_distances/_distances.py
  pertpy/tools/_metadata/_cell_line.py
  pertpy/tools/_milo.py
  pertpy/tools/_mixscape.py
  pertpy/tools/_perturbation_space/_clustering.py
  pertpy/tools/_perturbation_space/_discriminator_classifier.py
  pertpy/tools/_perturbation_space/_perturbation_space.py
  pertpy/tools/_perturbation_space/_simple.py
  pertpy/tools/_scgen/_jax_scgen.py
Labels: enhancement

#406 Fixture for Augur tests
  tests/tools/sc_sim.h5ad
  tests/tools/test_augur.py
Labels: enhancement

#409 Small bug fixes and docs improvements
  pertpy/plot/_dialogue.py
  pertpy/plot/_scgen.py
  pertpy/tools/_perturbation_space/_perturbation_space.py
  pertpy/tools/_perturbation_space/_simple.py
Labels: bug

#411 Fixed set_fdr for tascCODA models
  docs/installation.md
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_tasccoda.py
Labels: bug, chore
