Repository scverse/pertpy, pull requests merged in 2023-01, with the labels that each got.

#188 integrate scCODA and tascCODA
  .flake8
  docs/usage/usage.md
  pertpy/data/__init__.py
  pertpy/data/_datasets.py
  pertpy/plot/__init__.py
  pertpy/plot/_coda.py
  pertpy/plot/_mixscape.py
  pertpy/tools/__init__.py
  pertpy/tools/_augurpy.py
  pertpy/tools/_base_coda.py
  pertpy/tools/_sccoda.py
  pertpy/tools/_tasccoda.py
  poetry.lock
  pyproject.toml
  tests/tools/haber_data.csv
  tests/tools/test_augur.py
  tests/tools/test_milopy.py
  tests/tools/test_sccoda.py
  tests/tools/test_tasccoda.py
Labels: enhancement, chore

#195 fix mixscape default setting of layer
  pertpy/tools/_mixscape.py
  tests/tools/test_mixscape.py
Labels: bug

#196 changes default settings of coda and milo
  pertpy/plot/_coda.py
  pertpy/plot/_milopy.py
  pertpy/tools/_milopy.py
  tests/tools/test_milopy.py
Labels: bug

#190 added list option for sample_identifier in load
  pertpy/plot/_coda.py
  pertpy/tools/_base_coda.py
  pertpy/tools/_mixscape.py
Labels: enhancement
