Repository scverse/pertpy, pull requests merged in 2024-02, with the labels that each got.

#528 Add more detailed tool explanations
  docs/installation.md
  docs/usage/usage.md
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_tasccoda.py
  pyproject.toml
Labels: enhancement, chore

#529 Pseudobulk improvements
  pertpy/tools/_perturbation_space/_simple.py
Labels: enhancement

#533 Fixed Augur bug
  docs/_static/docstring_previews/augur_dp_scatter.png
  docs/_static/docstring_previews/augur_important_features.png
  docs/_static/docstring_previews/augur_lollipop.png
  docs/_static/docstring_previews/augur_scatterplot.png
  pertpy/tools/_augur.py
Labels: bug

#531 Address some Jax random key issues
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_sccoda.py
  pertpy/tools/_coda/_tasccoda.py
Labels: bug

#537 Fix Distance docstring rendering
  pertpy/tools/_distances/_distances.py
Labels: bug

#543 Expand load for sccoda docstrings
  pertpy/tools/_coda/_sccoda.py
Labels: enhancement

#547 fixed augur runtime
  pertpy/tools/_augur.py
Labels: bug
