Repository scverse/pertpy, pull requests merged in 2024-10, with the labels that each got.

#667 Fixed plotting for mixscape.plot_barplot and sccoda.plot_effects_barplot
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_mixscape.py
Labels: bug

#670 Augur scsim warnings
  .gitignore
  pertpy/data/_datasets.py
  pertpy/tools/_augur.py
  pyproject.toml
  tests/tools/test_augur.py
Labels: enhancement

#672 Add PerturbationDataValidator
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  .readthedocs.yml
  pertpy/data/__init__.py
  pertpy/data/_perturbation_validator.py
  pertpy/metadata/_compound.py
  pyproject.toml
Labels: enhancement, chore
