Repository scverse/pertpy, pull requests merged in 2024-08, with the labels that each got.

#636 Fix layer handling in Mixscape.mixscape to resolve errors with adata.raw
  pertpy/tools/_mixscape.py
Labels: bug

#637 Fix CI
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_tasccoda.py
  pertpy/tools/_distances/_distances.py
  tests/preprocessing/test_grna_assignment.py
Labels: bug

#638 Update README.md
  README.md
Labels: chore

#644 Python 3.12 support
  .github/workflows/test.yml
  pyproject.toml
Labels: enhancement

#647 Add lazy loading for deferred modules
  .github/release-drafter.yml
  pertpy/__init__.py
  pertpy/tools/__init__.py
  pyproject.toml
  tests/tools/_differential_gene_expression/test_dge.py
Labels: bug

#648 Fixes lazy loading
  .github/release-drafter.yml
  pertpy/__init__.py
  pertpy/tools/__init__.py
  pyproject.toml
Labels: bug
