Repository scverse/pertpy, pull requests merged in 2024-09, with the labels that each got.

#651 Fix docs rendering for classes using lazy import
  .github/workflows/test.yml
  docs/installation.md
  docs/usage/usage.md
  pertpy/tools/__init__.py
  pertpy/tools/_cinemaot.py
Labels: bug, chore

#653 Remove anndata pin
  .github/workflows/test.yml
  pyproject.toml
Labels: bug

#660 Fix legend position for pt.tl.Mixscape.plot_barplot
  pertpy/tools/_mixscape.py
Labels: bug

#666 Remove explicit anndata in dependencies
  pyproject.toml
Labels: bug

#658 Add uncertainty score in KNN label_transfer in PerturbationSpace
  .pre-commit-config.yaml
  pertpy/tools/_perturbation_space/_perturbation_space.py
  tests/tools/_perturbation_space/test_simple_perturbation_space.py
Labels: enhancement
