Repository scverse/pertpy, pull requests merged in 2025-05, with the labels that each got.

#757 Improve CI test setup & speed up mixscape
  .github/workflows/build.yml
  .github/workflows/test.yml
  docs/conf.py
  pertpy/data/_datasets.py
  pertpy/tools/_mixscape.py
  pyproject.toml
Labels: enhancement

#758 Change how guide assignment model saves params from uns to var
  pertpy/preprocessing/_guide_rna.py
Labels: bug

#762 Restructure documentation & fix scCODA not requiring tcoda extra
  .editorconfig
  .github/release-drafter.yml
  .github/workflows/release.yml
  .gitignore
  .readthedocs.yml
  README.md
  docs/_static/css/overwrite.css
  docs/api.md
  docs/api/datasets_index.md
  docs/api/metadata_index.md
  docs/api/preprocessing_index.md
  docs/api/tools_index.md
  docs/changelog.md
  docs/conf.py
  docs/index.md
  docs/tutorials.md
  docs/tutorials/index.md
  docs/tutorials/metadata.md
  docs/tutorials/preprocessing.md
  docs/tutorials/tools.md
  docs/usecases.md
  pertpy/__init__.py
  pertpy/tools/__init__.py
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_coda/_sccoda.py
  pertpy/tools/_coda/_tasccoda.py
  pertpy/tools/_dialogue.py
  pertpy/tools/_distances/_distances.py
  pyproject.toml
Labels: bug, enhancement, chore

#765 Simplify Metadata errors
  .github/release-drafter.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/changelog.md
  pertpy/__init__.py
  pertpy/data/_dataloader.py
  pertpy/metadata/_cell_line.py
  pertpy/metadata/_compound.py
  pertpy/metadata/_look_up.py
  pertpy/metadata/_metadata.py
  pertpy/metadata/_moa.py
  pertpy/tools/_augur.py
  pertpy/tools/_mixscape.py
  pyproject.toml
  tests/conftest.py
  tests/metadata/test_cell_line.py
  tests/tools/_coda/test_sccoda.py
  tests/tools/_distances/test_distance_tests.py
  tests/tools/test_augur.py
  tests/tools/test_dialogue.py
Labels: enhancement, chore

#779 fix docstring of example for effects_umap
  pertpy/tools/_coda/_base_coda.py
Labels: bug

#789 Add conda-forge to installation instructions
  README.md
  docs/installation.md
Labels: enhancement, chore

#791 Fix compatibility with rpy 3.6.0 in milo
  pertpy/tools/_milo.py
Labels: bug
