Repository scverse/pertpy, pull requests merged in 2025-02, with the labels that each got.

#695 Add perturbation signature calculation from replicate control cells
  docs/index.md
  pertpy/tools/_mixscape.py
  tests/tools/test_mixscape.py
Labels: enhancement, chore

#710 Align Mixscape with Seurat’s implementation
  pertpy/tools/_mixscape.py
  tests/tools/test_mixscape.py
Labels: bug

#704 Fix CI
  .github/workflows/test.yml
Labels: bug, enhancement

#716 PRISM drug response metadata annotation
  pertpy/metadata/_cell_line.py
  tests/metadata/test_cell_line.py
Labels: enhancement
