Repository scverse/pertpy, pull requests merged in 2025-01, with the labels that each got.

#683 Mixscape reproducibility
  pertpy/tools/_mixscape.py
  tests/tools/test_mixscape.py
Labels: bug

#696 Fix probability data type
  .github/pull_request_template.md
  .github/workflows/build.yml
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  docs/contributing.md
  docs/index.md
  docs/usage/usage.md
  pertpy/metadata/_cell_line.py
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_mixscape.py
  pyproject.toml
  tests/tools/test_mixscape.py
Labels: bug, chore

#699 Optimize test speed
  .github/workflows/test.yml
  pertpy/tools/_augur.py
  tests/tools/_distances/test_distances.py
  tests/tools/test_augur.py
Labels: enhancement

#701 Lower bound for scikit-learn
  pyproject.toml
Labels: enhancement

#703 Fix empty figure returns when show=True in plotting functions
  pertpy/_doc.py
  pertpy/metadata/_cell_line.py
  pertpy/preprocessing/_guide_rna.py
  pertpy/tools/_augur.py
  pertpy/tools/_cinemaot.py
  pertpy/tools/_coda/_base_coda.py
  pertpy/tools/_dialogue.py
  pertpy/tools/_differential_gene_expression/_base.py
  pertpy/tools/_enrichment.py
  pertpy/tools/_milo.py
  pertpy/tools/_mixscape.py
  pertpy/tools/_perturbation_space/_simple.py
  pertpy/tools/_scgen/_scgen.py
Labels: bug
